export const players = [
  {
    name: "Marcelinho Carioca",
    image: "/marcelinho.png",
    titles: 12,
    games: 401,
    goals: 206,
  },
  {
    name: "Cássio",
    image: "/cassio.png",
    titles: 10,
    games: 600,
    goals: 0,
  },
  {
    name: "Wladimir",
    image: "/wladimir.png",
    titles: 10,
    games: 800,
    goals: 50,
  },
  {
    name: "Ronaldo Giovanelli",
    image: "/ronaldo.png",
    titles: 8,
    games: 350,
    goals: 45,
  },
  {
    name: "Gilmar",
    image: "/gilmar.png",
    titles: 8,
    games: 500,
    goals: 0,
  },
  {
    name: "Neto",
    image: "/neto.png",
    titles: 7,
    games: 389,
    goals: 112,
  },
  {
    name: "Edílson",
    image: "/edilson.png",
    titles: 7,
    games: 250,
    goals: 150,
  },
  {
    name: "Sócrates",
    image: "/socrates.png",
    titles: 6,
    games: 297,
    goals: 172,
  },
  {
    name: "Basílio",
    image: "/basilio.png",
    titles: 6,
    games: 400,
    goals: 60,
  },
  {
    name: "Vampeta",
    image: "/vampeta.png",
    titles: 6,
    games: 280,
    goals: 30,
  },
  {
    name: "Rivelino",
    image: "/rivelino.png",
    titles: 5,
    games: 474,
    goals: 123,
  },
  {
    name: "Luizão",
    image: "/luizao.png",
    titles: 5,
    games: 200,
    goals: 120,
  },
  {
    name: "Zé Maria",
    image: "/zemaria.png",
    titles: 5,
    games: 350,
    goals: 20,
  },
  {
    name: "Casagrande",
    image: "/casagrande.png",
    titles: 4,
    games: 321,
    goals: 145,
  },
  {
    name: "Biro-Biro",
    image: "/birobiro.png",
    titles: 4,
    games: 300,
    goals: 70,
  },
  {
    name: "Rincón",
    image: "/rincon.png",
    titles: 4,
    games: 300,
    goals: 40,
  },
  {
    name: "Dinei",
    image: "/dinei.png",
    titles: 3,
    games: 180,
    goals: 80,
  },
  {
    name: "Tupãzinho",
    image: "/tupa.png",
    titles: 3,
    games: 200,
    goals: 90,
  },
  {
    name: "Carlos Tevez",
    image: "/tevez.png",
    titles: 1,
    games: 50,
    goals: 25,
  },
];

export const navBarLinks = [
  { toId: "inicio", text: "Início" },
  { toId: "sobre", text: "Sobre" },
  { toId: "titulos", text: "Títulos" },
  { toId: "jogadores", text: "Jogadores" },
];
